null:
	echo you need to specify the version AND architecture > /dev/null
	echo make sure to do ``make [target] -B`` > /dev/null
pastaignore_1.0-1_amd64:
	dpkg-deb --build --root-owner-group pastaignore_1.0-1_amd64
